language: java
sudo: required
services:
  - xvfb
before_install:
  - sudo apt-get -qq update || echo no sudo apt-get
  - sudo apt-get install -y libwebkitgtk-3.0-0 || echo no sudo apt-get
  - sudo apt-get install -y xdg-utils || echo no xdg-utils
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start || echo No X11
  - sleep 3
script:
  - mvn verify
matrix:
  include:
    - os: linux
      dist: trusty
      jdk: openjdk8
    - os: linux
      dist: trusty
      jdk: openjdk11
    - os: osx
      osx_image: xcode9.3
      jdk: openjdk11
